### ISSUE TITLE
Should ignore prefix of cl-defmethod

### ISSUE THREAD

**Issue by purcell** [purcell/package-lint#107]
When a package declares a `cl-defmethod`, that's often for a generic function in another package, so we should not complain if the name of the method does not start with the package prefix.

**Comment by alphapapa** [comment]
Should we check to see whether it starts with a prefix of another, installed package?

**Comment by purcell** [comment]
> Should we check to see whether it starts with a prefix of another, installed package?

Nope, I don't think so.

**Comment by Fuco1** [comment]
There's also bunch of built-in generic methods, `clone` comes to mind, which you can override for your own EIEIO methods.

**Comment by purcell** [comment]
Looks like this was done in #115.
