### ISSUE TITLE
`straight.el` is not supported

### ISSUE THREAD

**Issue by FelipeLema** [purcell/package-lint#108]
Exclusively using [`straight.el`](https://github.com/raxod502/straight.el) to install packages is not supported :`package-lint--check-packages-installable` says "Package … is not instalable" even though I have the package installed using `(straight-use-package …)`

**Comment by FelipeLema** [comment]
I'm working on a solution for this, however:

As described in raxod502/straight.el#290 (in [this](https://github.com/raxod502/straight.el/issues/290#issuecomment-402870518) comment) it is not trivial to have descriptions from packages installed using `straight.el`, so _versions_ can't be tested in `package-lint--check-package-installable`.

If a solution is to be accepted, would it suffice to _warn_ about versions checked? would straight.el not be supported at all (due to this limitation)?

**Comment by bradyt** [comment]
Seems weird to have a package available and package-lint complain that it is not, just because package.el was not used. Looks like it expects it to be in `package-archive-contents`.

**Comment by FelipeLema** [comment]
cross referencing fix for this: https://github.com/purcell/package-lint/pull/133

**Comment by purcell** [comment]
Hmmm. The intention of `package-lint` is to check that files are in a fit state to be distributed via package archives and installed by users using `package.el`. Supporting packages that can only be obtained via a completely separate mechanism seems somewhat out of scope.

**Comment by purcell** [comment]
Alternatively, the check could be changed to not only check `package-archive-contents`, but also to try `package-installed-p`, which I'm guessing returns `t` for packages installed with `straight`?

Whatever the case, I'd prefer that developers are at least warned that their declared dependencies aren't listed on a package archive.

**Comment by FelipeLema** [comment]
Just tried `(package-installed-p 'some-straight-installed-package)` and it errored out: "package.el is not yet initialized", so I guess that's a no go.

I just modified the warning as you specified in https://github.com/purcell/package-lint/pull/133

**Comment by FelipeLema** [comment]
hmmm... I've re-read a lot of this and I now understand that `package-lint.el` is strict on how fit a file is to be packaged. This directly clashes with `straight.el`'s purposes, so I guess I saying "`straight.el` support in `package-lint.el`" is a contradiction (and thus, not an issue).

**Comment by purcell** [comment]
Yep, pretty much. :-)
