### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by DamienCassou** [purcell/package-lint#116]
Can you please release a new version of package-lint?

**Comment by purcell** [comment]
Done, thanks - 0.7.

**Comment by DamienCassou** [comment]
Steve Purcell <notifications@github.com> writes:
> Done, thanks - 0.7.

thank you!

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
