### ISSUE TITLE
package-lint depends on let-alist 1.0.6 which is not available in emacs 26.3

### ISSUE THREAD

**Issue by nhojb** [purcell/package-lint#154]
This means that package-lint is marked as incompatible in the package list.

I've checked the following "release" versions of emacs on macOS:

- brew emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.0.0) of 2019-10-01
- emacsforosx.com: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02

Both include let-alist 1.0.5

The currently nightly build from emacsforosx.com (GNU Emacs 27.0.50 of 2019-12-02) does include let-alist 1.0.6. However, it's not a "release" build.

**Comment by purcell** [comment]
I can't reproduce this in the same Emacs build and version. Do you somenow not have GNU ELPA in your `package-archives` list?

**Comment by purcell** [comment]
The dependency has been there since late September and there's been no other sign of breakage, including in CI with much older Emacsen.

**Comment by nhojb** [comment]
Ah, that's it! I removed GNU ELPA a while back to get rid of duplicate/stale entries in the package list. Apologies for the invalid bug report.
