### ISSUE TITLE
Invalid "emacs is redundant in package names" warning for treemacs

### ISSUE THREAD

**Issue by Alexander-Miller** [purcell/package-lint#155]
Not sure if it's worth the effort given the likely number of cases, but the detection is too broad and catches names like "treemacs", which is, while a bit punny, a perfectly valid package name.

**Comment by purcell** [comment]
Thanks. I agree that "treemacs" is okay in this regard, but I stand by the warning, generally, and I feel like it's some combination of not worthwhile/feasible to try to identify the few reasonable usages with a regexp. Of the other MELPA packages with "emacs" in their name, I can't see any that wouldn't be significantly improved by that word being removed.
