### ISSUE TITLE
mapcan missing from stdlib-changes (added in 26.1)

### ISSUE THREAD

**Issue by mattiase** [purcell/package-lint#161]
Not sure what exact step went wrong in the generation of that file for the function to be missing.

**Comment by purcell** [comment]
`mapcan` was also present in `cl` previously.

**Comment by mattiase** [comment]
Thanks, I should have known.

**Comment by purcell** [comment]
No worries. Note that this kinda relates to #149: there's a limit to how much we can tell the user about the history of how symbols have moved around inside the emacs standard library.
