### ISSUE TITLE
Exiting 0 with warnings found makes detecting warnings difficult

### ISSUE THREAD

**Issue by alphapapa** [purcell/package-lint#163]
Hi Steve (@purcell),

Regarding https://github.com/purcell/package-lint/blob/f86705d0d4ed81ea8ea14e00fe59714f11f7c2ba/package-lint-test.el:

I understand [why](https://github.com/purcell/package-lint/pull/162#issuecomment-590109258) this change was made, but this will make it more difficult to detect whether `package-lint` has issued warnings when run in batch mode.  For example, in `makem.sh`, the [exit code is used](https://github.com/alphapapa/makem.sh/blob/fcdfb3d312d92bffe84a23f0ec7b344fb07c3ed4/makem.sh#L761) to determine whether any problems were found.  After this change, warnings will no longer be detected as problems.  So when run manually, users will have to be careful to use `-vv` and manually review output for warnings.  And when run in CI, warnings will no longer cause linting failure, which may be unhelpful to packages using it in a pull request review workflow who wish to have completely clean `package-lint` runs.

There are a few options I can see here:

1.  `makem.sh` could ignore exit codes and check printed output instead.  Of course, this is relatively brittle, especially if regexps are required to check for certain matches in the output.  It's also much more complicated, especially when using lesser verbosity modes which don't emit output unless errors are found.  Exit codes are much simpler and more reliable, so I've attempted to avoid this at all costs, even adding my own Elisp wrappers for linters to call the internal functions and exit with the appropriate code.  
2.  `makem.sh` could add such a wrapper for `package-lint`.  This is doable, but it would always be preferable to not have to do so, because upstream changes can easily break the wrapper.
2.  `package-lint` could offer an option to treat warnings as errors for the sake of the exit code.  This would be similar to Emacs's built-in option for byte-compile warnings, `byte-compile-error-on-warn`.  This isn't too difficult for `makem.sh` to [use](https://github.com/alphapapa/makem.sh/blob/fcdfb3d312d92bffe84a23f0ec7b344fb07c3ed4/makem.sh#L282), and it's simple to implement in Elisp as well.
3.  That option could also be implemented as an argument to the command `package-lint-batch-and-exit`, or as an additional command.

The latter two options would also allow `makem.sh` to offer a command-line option for the warning level.

What do you think?  Thanks.

**Comment by DamienCassou** [comment]
I completely agree. In all of my packages, I have decided to treat all warnings as errors and prevent merging code with warnings.

**Comment by purcell** [comment]
Yeah, my next planned step was to add a var to control this behaviour. I guess there's an open question about what the default should be. I'd probably prefer that the default should be to exit with 1 for warnings too: it probably doesn't matter as long as it's documented.

**Comment by purcell** [comment]
Fixed by #165, thanks guys.

**Comment by stepnem** [comment]
FWIW, I wasn't enthusiastic about the solution in f86705d, either, and
agree that warnings usually indicate a real problem, but I insist that
the summary capitalization requirement has no place in package-lint
(cf. the discussion at #162) and this effectively brings that issue
back to square one, as having to set a variable is just another
workaround (and would also affect useful warnings).

I assume most people want sane default behaviour. I argue that to
satisfy that need, package-lint should only warn about documented and
well established conventions, as stated in its own README file (again,
please see #162 for more detail).

**Comment by alphapapa** [comment]
Thanks, Steve.

@stepnem The purpose of package-lint is to improve the quality of packages and make the MELPA maintainers' job easier.  In their judgment, capitalizing summaries does so.  Steve has already politely declined your demand.  If you can't tolerate his decision, please fork the package and carry on.

**Comment by purcell** [comment]
If at some point we introduce an "info" level (fairly likely), I'd consider demoting the capitalisation suggestion from "warning".

**Comment by DamienCassou** [comment]
Thank you @purcell.

**Comment by lassik** [comment]
While I don't personally care which checks are errors and which ones are warnings, I'd argue against adding more levels (info, notice, debug, etc.) on the grounds that they get more confusing with each new level. C compilers emit a particularly large variety of messages, and those are only grouped into errors and warnings. It works great.

Compiler message levels are easy to grasp: errors stop the compile, warnings don't (unless you manually use `-Werror`). The same criterion could be good for package-lint: Something that would block a MELPA submission is an error; advice that doesn't block submission is a warning. If warnings exit with code 1 and errors with code 2, it could even be tied into the new MELPA scripts that are just being experimented with (ping @riscy).
