### ISSUE TITLE
I get an error trying to lint my buffer

### ISSUE THREAD

**Issue by SpecialBomb** [purcell/package-lint#167]
I was trying to use package-lint from MELPA to lint a single file package of mine, of which I loaded into a buffer. `package-lint-current-buffer` gave me an error message in the messages line, and did not pop up a window stating any issues with my package file. To see what happened, I used `M-x eval-expression` and ran `(package-lint-buffer (get-buffer "buffername"))` and got the same error message, but with a traceback. Here is that:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  compare-strings(nil 0 0 "modern-fringes-init" 0 0 nil)
  string-prefix-p(nil "modern-fringes-init")
  package-lint--valid-definition-name-p("modern-fringes-init" nil #<marker at 2371 in modern-fringes.el>)
  package-lint--check-defs-prefix(nil (("modern-fringes-init" . #<marker at 2371 in modern-fringes.el>) ("modern-fringes-revert" . #<marker at 3376 in modern-fringes.el>) ("modern-fringes-invert-arrows" . #<marker at 3805 in modern-fringes.el>) ("modern-fringes-mode" . #<marker at 4382 in modern-fringes.el>)))
  package-lint--check-all()
  package-lint-buffer(#<buffer modern-fringes.el>)
  eval((package-lint-buffer (get-buffer "modern-fringes.el")) nil)
  eval-expression((package-lint-buffer (get-buffer "modern-fringes.el")) nil nil 127)
  funcall-interactively(eval-expression (package-lint-buffer (get-buffer "modern-fringes.el")) nil nil 127)
  call-interactively(eval-expression record nil)
  command-execute(eval-expression record)
  execute-extended-command(nil "eval-expression" "eval-expre")
  funcall-interactively(execute-extended-command nil "eval-expression" "eval-expre")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
Something isn't right. I am using Emacs 26.3.

**Comment by purcell** [comment]
Right, but our tests are passing, so this is probably something in your source code that we're not quite handling correctly. Can you share a link to it, please, otherwise I won't be able to investigate?

**Comment by purcell** [comment]
Thanks for filing a report, btw.

**Comment by purcell** [comment]
Hang on, I think I found it: https://github.com/SpecialBomb/emacs-modern-fringes/blob/master/modern-fringes.el

**Comment by purcell** [comment]
Fixed now. One error in the file was incorrectly causing a further check to fail. With the fix, the errors for your file look like this:
```
3 issues found:

1:0: error: There is no (provide 'modern-fringes) form.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
122:0: error: Customization groups should specify a parent via `:group'.
```

**Comment by purcell** [comment]
The main issue is the first one. Generally it is safest create new elisp files using `M-x auto-insert`, to make sure the overall structure is correct.

**Comment by SpecialBomb** [comment]
I don't know much about the provide form. To the docs!

I also just bumped my version up to fix the second error. The warning will have to stay due to the fact the mode has no keyword interaction at all.

**Comment by SpecialBomb** [comment]
alright, everything is in shape, thank you!

**Comment by purcell** [comment]
> The warning will have to stay due to the fact the mode has no keyword interaction at all.

I think you've misunderstood the warning: your "Keywords:" header includes things like "themes", but none of the standard ones. For this package, you would probably choose "frames" and just add that to the list.

**Comment by SpecialBomb** [comment]
oooh, I see, I already fixed that problem, and then I got a seperate error talking about the keymap. I am really tired today by the way.

**Comment by purcell** [comment]
> I am really tired today by the way

Sleep is more important than elisp! 😄
