### ISSUE TITLE
Not consider removed then re-added function like mm-url-encode-multipart-form-data

### ISSUE THREAD

**Issue by xuchunyang** [purcell/package-lint#168]
https://github.com/melpa/melpa/pull/6733#issuecomment-597222892

My package depends on Emacs 25.1 and uses `mm-url-encode-multipart-form-data`, package-lint reports this error

    error: `mm-url-encode-multipart-form-data' was removed in Emacs version 24.3.

however, this function is likely added back in Emacs 25.1 according to package-lint

    You should depend on (emacs "25.1") if you need `mm-url-encode-multipart-form-data'.

**Comment by purcell** [comment]
This is quite a rare case, I think, but yes, I'd agree that `package-lint` should take into consideration.
