### ISSUE TITLE
Add a "when was this added?" command

### ISSUE THREAD

**Issue by tarsius** [purcell/package-lint#181]
Please add a query command that informs the user when a certain interactively read function/variable was added.

I am aware this package is about linting but it has all the necessary data and it would complicate matters if that had to be duplicated in another package just because this command might not fix perfectly here. The workaround of adding the function/variable to a library, fiddling with Package-Requires, and running `package-lint-current-buffer` repeatably until we got the answer is just to cumbersome.

**Comment by purcell** [comment]
> The workaround of adding the function/variable to a library, fiddling with Package-Requires, and running `package-lint-current-buffer` repeatably until we got the answer is just to cumbersome.

I'm not quite clear on how this loop ends up happening, and I wonder whether a potential (or better) solution might be to include more info about symbols directly in the `package-lint` output.

**Comment by tarsius** [comment]
Oooch, I was being dramatic. Linting once should be enough.

The command you added serves my needs perfectly and its a nice surprise it even provides history.
