### ISSUE TITLE
False positive for macro behind macrop conditional

### ISSUE THREAD

**Issue by jscheid** [purcell/package-lint#198]
I'm using a 27.1 feature without declaring it as a requirement, because I'm checking for the availability of the feature (via `macrop`) and falling back to a workaround when unavailable. I suppose it's what they call a polyfill in JS land.

[Code is here](https://github.com/jscheid/prettier.el/pull/66/commits/c7694779071e415ea1cf4ccff7d77963273fbea7#diff-0bfd05293a2b9d0104bbfe3773359ad0f4e45fd1fe2dae6c34da51612abb0525R60-R64) and [lint error is here](https://github.com/jscheid/prettier.el/runs/1594338512?check_suite_focus=true).

Apologies if this is already discussed elsewhere and I missed it: is there some way to suppress this error? Or otherwise, could  you suggest how to get around it?

**Comment by jscheid** [comment]
It turns out that using `fboundp` instead of `macrop` works as well, and is recognized by package-lint 👍

**Comment by purcell** [comment]
Hmm. Probably we should also allow macrop. Thanks for reporting this.

**Comment by purcell** [comment]
> Probably we should also allow macrop.

Ah no, I'm mistaken, because `macrop` is more tightly bound. `fboundp` is the right solution, as you determined.

**Comment by jscheid** [comment]
If you happen to have a spare minute, could you elaborate? Not that it matters much, but I'm curious -- what do you mean by "more tightly bound"?

**Comment by purcell** [comment]
`macrop` acts on an object directly, whereas `fboundp` looks the object up first via the symbol.

It probably doesn't make much of a difference in practical terms, I guess.

**Comment by jscheid** [comment]
Right, that makes sense. Thank you.

**Comment by purcell** [comment]
Like, `(macrop 'defun)` returns `t`. But you can also `(macrop #'defun)`. Actually, you can also `(fboundp #'defun)`. So I guess the behaviour is actually more consistent than I thought. TIL - thanks!
