### ISSUE TITLE
define-obsolete-function-alias: new mandatory argument

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/package-lint#199]
Hi,

first of all thank you for `package-lint-flymake`!

I see in its code you are using `define-obsolete-function-alias`:

```emacs-lisp
(define-obsolete-function-alias 'package-lint-setup-flymake 'package-lint-flymake-setup)
```

I just wanted to let you know that as of [this commit](https://github.com/emacs-mirror/emacs/commit/32c6732d16385f242b1109517f25e9aefd6caa5c) on Emacs master, the `when` argument is mandatory.

[The same "problem" appears on `page-break-lines`.]

**Comment by purcell** [comment]
Good catch, thanks, I noticed that mentioned on the emacs reddit.
