### ISSUE TITLE
Acceptable prefixes: should `toggle-` be on the list?

### ISSUE THREAD

**Issue by riscy** [purcell/package-lint#216]
The const `package-lint--sane-prefixes` lists some exceptional prefixes that package-lint will let slide.  These have been super useful, so thanks.

It seems another common prefix is `toggle`, which came up in [this recent MELPA PR](https://github.com/melpa/melpa/pull/7583).

`toggle` seems to be a popular prefix across packages -- especially builtins.  One very small disadvantage I see is that there is a package called `toggle` indexed on MELPA.  Altogether I don't see it as a problematic prefix, but I'm a consistency hobgoblin and it would be nice if the exception were codified in package-lint, should that make sense.

@rnkn fyi.

**Comment by purcell** [comment]
Almost every `toggle-` function I've ever come across should have been a minor mode. The example in `side-hustle` is no exception afaict.

**Comment by purcell** [comment]
And beyond consistency there are _numerous_ advantages to using minor modes for this sort of case, e.g. optional visibility in the mode line while enabled, custom keymap while enabled.

From the README:
> Side Hustle works on multiple buffers simultaneously, does not require a global minor mode, and does not rely on timers.

I haven't tried it out, so I don't yet understand the point about simultaneous buffers, but it's not automatically a win to not require a minor mode, rather the opposite IMO.

**Comment by riscy** [comment]
Thanks!  In the linked PR the function is popping/unpopping a side window (I should have mentioned this) and I hadn't even considered the knock-on effect this would have regarding minor modes.  I agree with the rationale here.

**Comment by rnkn** [comment]
@purcell re the side-hustle multiple buffers thing, this is just because Imenu-List (from which I took the inspiration) only works on one buffer at a time. There's a major mode at work within the side windows so not requiring a minor mode just to launch the major mode is the win.

**Comment by purcell** [comment]
I guess your point is that when the side-hustle window is closed, it wouldn't make sense for a global minor mode to still be active? :+1:

**Comment by rnkn** [comment]
Yeah totally. Adding a minor mode would permit more features (e.g. highlighting current item) so I'll probably end up with that, it just doesn't need it atm.. all it would provide is the keystroke to launch the side window.
