### ISSUE TITLE
Adding package-lint to NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [purcell/package-lint#220]
Hi,

I was considering adding package-lint to [NonGNU ELPA](https://elpa.nongnu.org), and wanted to check if there is any upstream interest. The main blocker is the [`Version: 0`](https://github.com/purcell/package-lint/blob/master/package-lint.el#L9), that ELPA interprets as an [unreleased package](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/README?h=elpa-admin#n439). This can be circumvented manually, but the preference is to have the maintainers update the version tag from their end.

**Comment by minad** [comment]
It seems package-lint is already there? Can this be closed?

**Comment by purcell** [comment]
[Yep](https://elpa.nongnu.org/nongnu/package-lint.html), thx @minad
