### ISSUE TITLE
Support Emacs 29

### ISSUE THREAD

**Issue by minad** [purcell/package-lint#245]
Hi @purcell, I know it is a bit early, but could we please get (preliminary) support for Emacs 29? Emacs 29 is mostly frozen now.

**Comment by purcell** [comment]
Is this anything more than just updating the added/removed symbols etc.? I don't really want to start doing that ahead of official releases if I can avoid it, it seems like a recipe for extra work. Generally I do so within a day or two of the official release anyway. Perhaps you can explain why this would be useful?

**Comment by minad** [comment]
Yes, sure. I am happy to explain. 

My packages already support Emacs 29 and I accidentally started using Emacs 29 symbols, which then lead to breakage. I've also seen that issue in other packages. Some package developers are moving a bit faster such that 29 is already fully supported as soon as it is released. I am already using 29 and from the reports I've got, many people from the community do the same, or are even following Emacs master.

Then there is a second reason specific to myself - I started maintaining the Compat package (mentioned in #227) and your package-lint diffs provide exceptionally useful information which help me with the maintainance of Compat.

My hope is that you could create an Emacs 29 update of the symbol data soon and then again a final update when Emacs 29 is released. But this is still a few months away.

**Comment by tarsius** [comment]
> when Emacs 29 is released. But this is still a few months away.

Do you know when the first pre-release is planned? A month ago it was "in a few days" (which forced me to rush some changes, I had to get in before that :face_with_spiral_eyes:) but it seems there was a change in plan.

**Comment by minad** [comment]
Emacs 29 has been released, see https://lists.gnu.org/archive/html/emacs-devel/2023-07/msg00879.html.

**Comment by tarsius** [comment]
> Emacs 29.1 has been released

Heard about it here first.

**Comment by purcell** [comment]
Done now, fwiw

**Comment by purcell** [comment]
(I've added support for 291. in `setup-emacs` and `nix-emacs-ci`, and updated CI here in order to have the stdlib-changes regenerated.)

**Comment by minad** [comment]
Thanks!
