### ISSUE TITLE
Reconsidering / as a Non-standard Sepator?

### ISSUE THREAD

**Issue by WammKD** [purcell/package-lint#265]
`/`'s used in a lot of packages as a separator in function names and a variety of inbuilt Emacs packages (such as `pcomplete/ag` in `pcmpl-x.el` and `eshell/cat` in `em-unix.el`) likewise make use of `/`.

Obviously, it shouldn't be the first separator you reach for but it seems somewhat of overkill to call out a separator which is fairly widely (standardly) used?

**Comment by WammKD** [comment]
> Some specific uses are already white-listed by `package-lint`, IIRC.

I hadn't known that; do you know the general area I'd look to find what they are?

**Comment by purcell** [comment]
Here, for example: https://github.com/purcell/package-lint/blob/fce93b7edf4e971b2cbe3425c1d773ffe0aa8a62/package-lint.el#L199-L202

**Comment by purcell** [comment]
I'll close this, then, because our (MELPA) review standards have been consistent for a long time, and have strongly discouraged non-standard separators.
