### ISSUE TITLE
Requesting a new tagged release

### ISSUE THREAD

**Issue by manphiz** [purcell/package-lint#266]
Hi,

While working on packaging exec-path-from-shell in Debian, I found that it cannot pass the checking with package-lint 0.21 as a few more fixes (such as detecting add-ons shipped with Emacs) are not included.  I understand that exec-path-from-shell directly the latest snapshot version.  But it would be beneficial if it can reuse a preinstalled version so that the build process doesn't need access to the Internet directly.

Is there a plan to tag a new release (or any milestones before the next tagged release)?

**Comment by purcell** [comment]
Ah, thanks, this was an oversight. I've tagged 0.22 now, and MELPA should build the corresponding package soon.

**Comment by manphiz** [comment]
Great!  Thanks!
