### ISSUE TITLE
Requesting a new tagged release after Emacs 29.3

### ISSUE THREAD

**Issue by manphiz** [purcell/package-lint#268]
So it looks like 0.22 will fail some checking when running using 29.3 due to missing mappings.  It would be good to have another tagged release with 29.3 info.

This is similar to https://github.com/purcell/package-lint/issues/266.

EDIT: let's also bump the package version: https://github.com/purcell/package-lint/blob/master/package-lint.el#L9

**Comment by purcell** [comment]
Thanks, I bumped to 0.23, including updating the Version string in the source.
