### ISSUE TITLE
Extract the actual linter into a separate package

### ISSUE THREAD

**Issue by Fanael** [purcell/package-lint#33]
It's trivial, as `flycheck-package--check-all` and its callees don't depend on Flycheck.

@purcell, can you create a `package-lint.el` repo so we (and by "we" I mean "I", because you're probably too busy) can do it as soon as possible? Or rename this one, so the issue tracker remains intact, and move the Flycheck glue to a separate one?

**Comment by purcell** [comment]
Yep, I'll do that at the end of the week. :-)

**Comment by Fanael** [comment]
Which one? I'd prefer the latter, i.e. the rename, because AFAIK GitHub doesn't let you move issues between repos and keeping the issues is obviously useful.

**Comment by purcell** [comment]
Yep, I'll have a think about the trade-offs and decide on the best approach.

**Comment by purcell** [comment]
Done. I renamed this to `package-lint`, and pushed an exact clone to `flycheck-package`, then edited the contents of each accordingly. You're therefore still a collaborator on this repo. Seems okay, but let me know if I've missed anything. Thanks for your help!

**Comment by Fanael** [comment]
LGTM
