### ISSUE TITLE
Hook up the testsuite to Travis

### ISSUE THREAD

**Issue by Fanael** [purcell/package-lint#39]
Just a matter of making Travis install Emacs and run `run-tests.sh`. Unfortunately, I can't do that.

**Comment by purcell** [comment]
Happy to do that at the weekend. :-)

**Comment by purcell** [comment]
Cool, that's working nicely now, though the tests are failing on Emacs <= 24.3: https://travis-ci.org/purcell/package-lint

**Comment by Fanael** [comment]
Good. I'd be more worried if all tests passed on all Emacs versions.

I'll fix it tomorrow.

**Comment by Fanael** [comment]
Progress: as of 3a608fc6764, the tests pass on Emacs 24.3.

**Comment by Fanael** [comment]
Marvel at all this green: https://travis-ci.org/purcell/package-lint/builds/169883798
