### ISSUE TITLE
Adjust/remove keyword checks

### ISSUE THREAD

**Issue by alphapapa** [purcell/package-lint#40]
It pains me to say this, but I'm not sure the keyword-checking we added is a good idea.  It's true that `finder-known-keywords` has a list of canonical, RMS-approved keywords, which suggests it's a good idea to only use those.  But, as I recently noticed, it's also true that `package.el` reads non-blessed keywords and displays them in each package's description, and they can even be clicked to filter the package list by non-standard keywords (e.g. the `git` keyword is non-standard, but one can use it to find git-related packages easily).

So I guess this check should be removed.  

Alternatively, we could use `(package-all-keywords)` to get a list of all known keywords (actually known, as opposed to only the standard ones from `finder-known-keywords`), and we could issue mild warnings about the use of ones that don't already exist in the package archives.  That might at least help prevent the proliferation of new keywords (like how `drag` and `drop` are separate keywords, as well as `drag and drop`).  However, `(package-all-keywords)` seems like a slow function, taking over 5 seconds to return on my system, so it would definitely need to be cached and only run once per session or per file.  Even then, though, I'm not sure if that long of a pause is justifiable.

What do y'all think? :)

**Comment by purcell** [comment]
Hmmm. Maybe we could warn if there are keywords, but _none_ of them are in `finder-known-keywords`? That way, authors would be made aware of the standard keywords and gently encouraged to use them, without being punished for using non-standard ones.

**Comment by Fanael** [comment]
Do what you think is best, I have no opinion on this matter.
