### ISSUE TITLE
Ignore `org-dblock-write:` prefix

### ISSUE THREAD

**Issue by marsam** [purcell/package-lint#47]
org mode use the prefix `org-dblock-write:` to define [dynamic blocks](http://orgmode.org/manual/Dynamic-blocks.html). I think could be safely dismissed as error.

Currenly, with flycheck-package:

```
206   1 error           `org-dblock-write:gargantua' contains a non-standard separator `:', use hyphens instead. (emacs-lisp-package)
206   1 error           "org-dblock-write:gargantua" doesn't start with package's prefix "gargantua". (emacs-lisp-package)
```

**Comment by purcell** [comment]
Yeah, there's a similar convention for `ob` packages too, IIRC... want to submit a PR?
