### ISSUE TITLE
Info-level messages?

### ISSUE THREAD

**Issue by alphapapa** [purcell/package-lint#66]
From #63:

> (Further, I wonder if there's a case for adding "info"-level messages to package-lint for instances like this. Flycheck supports them IIRC, and we could avoid failing the package-lint-buffer check if only info-level messages are present. Opinions, @Fanael?)

**Comment by Fanael** [comment]
Sure, nothing against that.

**Comment by purcell** [comment]
No specific action to be taken here, I think, so closing.
