### ISSUE TITLE
Check that a package provides a feature

### ISSUE THREAD

**Issue by Lindydancer** [purcell/package-lint#69]
Hi!

A little feature request: Would it be possible for package-lint to check that a package contains a `provide' expression, and that the name match the name of the package?

    -- Anders

**Comment by purcell** [comment]
I think this was done in [this commit](https://github.com/purcell/package-lint/commit/a69ab2c206d05dac401b4b7df79afb2875e872a1), no?

**Comment by Lindydancer** [comment]
Yes, it appears so. I must have been using an older version. Sorry about the noise...

/ Anders

**Comment by purcell** [comment]
No worries. I probably need to tag a fresh stable release containing this change.
