### ISSUE TITLE
Don't warn about package prefix for defadvice

### ISSUE THREAD

**Issue by purcell** [purcell/package-lint#72]
When advising functions from other packages with a `defadvice` form, `package-lint` complains that that function does not begin with the current package prefix. `defadvice` should not be considered a `defun` form for this purpose.

See https://github.com/melpa/melpa/pull/4801

**Comment by Fanael** [comment]
Fixed.

I'd say `defadvice` itself is a huge smell, but that's another story.

**Comment by purcell** [comment]
> Fixed.

Awesome!

> I'd say defadvice itself is a huge smell

Agreed.
