### ISSUE TITLE
Allow package prefixes that aren't the same as the provided feature

### ISSUE THREAD

**Issue by IvanMalison** [purcell/package-lint#75]
I sometimes find it convenient to use a package prefix that is an abbreviation of the provided feature instead of the full provided feature name to keep the names of functions from getting very long. ex. lfn- long-feature-name-

In general it seems like it might be useful to be able to declare that a given file uses some arbitrary package prefix. Is this something you would be opposed to?

**Comment by purcell** [comment]
I think it's an antipattern, and I'm not sure I'd want to allow this warning to be suppressed.  Generally it's better for everyone if authors choose a slightly shorter feature name and then use a prefix consistent with it.

Implementing this would be problematic: we could try to detect that all decls have a consistent prefix, at least, but what if it's only two characters long, or matches the name of another package, or doesn't correspond in any helpful way to the name of the feature? The current approach avoids these issues, even if it's quite strict.

**Comment by wavexx** [comment]
I'm not fully onboard on this. I think it's correct for the feature name to be telling (interactively more discoverable), while allowing logical shortcuts to be made. I would actually prefer if `ffap` would be available as `find-file-at-point.el` and not the other way around.

**Comment by purcell** [comment]
> I'm not fully onboard on this. I think it's correct for the feature name to be telling (interactively more discoverable), while allowing logical shortcuts to be made. I would actually prefer if ffap would be available as find-file-at-point.el and not the other way around.

I agree. A middle ground would be for `package-lint` to only strongly warn (rather than error) if there is a consistent prefix which doesn't match the package name. But I'm still very much -1 on the whole idea: most shortened prefixes are completely arbitrary and make no sense on their own, since their only goal is to save the author some typing by artificially shortening the identifiers. If a shorter prefix actually makes sense, then the whole package can be renamed to that shorter name!

**Comment by IvanMalison** [comment]
> since their only goal is to save the author some typing by artificially shortening the identifiers.

It's not at all about saving typing. The main problem with super long namespaced names is that they take up a ton of line space, especially if you are trying to limit line length to 80 characters.

> think it's correct for the feature name to be telling (interactively more discoverable)

This is the best argument for this IMO.

**Comment by wavexx** [comment]
Long prefixes are very distracting visually. When reading the source of some packages, you can spot paragraphs where each line starts with a 5 word prefix, however you actually care about the final part.

I sometimes use `nameless` for this, but I think it isn't a great solution, just like glasses-mode.

**Comment by alphapapa** [comment]
> I sometimes use nameless for this, but I think it isn't a great solution, just like glasses-mode.

Agreed.  The main problem IMO is indentation.  I did hack something up that toggles the mode and reindents the whole buffer when saving, but 1) that's slow for large files, and 2) when editing other people's files that may have irregular indentation, it fills diffs with irrelevant whitespace changes.

**Comment by purcell** [comment]
Yeah, the elisp manual says to choose a short, consistent prefix, so more than three words is a bit silly. But I feel like it should always be possible to choose a 1-3 word package name that is also acceptably concise as a prefix.
