### ISSUE TITLE
Key sequence checker warns too much

### ISSUE THREAD

**Issue by Fanael** [purcell/package-lint#81]
#This is perfectly fine, according to the manual:
```emacs-lisp
;;; foo.el --- blah blah
;;; Package-Version: 0
;;; Commentary:
;; yadda yadda yadda
;;; Code:

(defconst foo-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c # x") #'ignore)
    map))

(define-minor-mode foo-mode ""
  :keymap foo-mode-map)

(provide 'foo)
;;; foo.el ends  #here
```

package-lint, however, warns about the key binding:
```
1 issue found:

9:45: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```
even though this keybinding is reserved *for minor modes* and used by *a minor mode*.

**Comment by alphapapa** [comment]
Sorry, I don't understand.  I guess we can't determine whether a key is bound to a keymap that ends up in a minor mode without effectively evaling the whole file.  But that commit lets several reserved keybindings through without warning.  Is this just too complicated to bother with at all?

**Comment by purcell** [comment]
> Sorry, I don't understand. I guess we can't determine whether a key is bound to a keymap that ends up in a minor mode without effectively evaling the whole file. But that commit lets several reserved keybindings through without warning. Is this just too complicated to bother with at all?

The thing I keep pulling people up on in code reviews is trampling the `C-c <letter>` keybindings that are reserved for users. I pretty much never give feedback on whether minor modes are using major-mode bindings or vice versa: it would indeed be harder to make `package-lint` handle that properly, and I consider it out of scope for now.

So the currently-committed code does what I hoped for! :-)
