### ISSUE TITLE
Should we suggest new package use lexical-binding t 

### ISSUE THREAD

**Issue by tumashu** [purcell/package-lint#97]
Many packages in emacs have set lexical-binding to t,  should we suggest new packages to use it?

![qq 20180123164101](https://user-images.githubusercontent.com/67725/35265846-4ec0083e-005c-11e8-8026-f48aa70a1796.jpg)
![qq 20180123164124](https://user-images.githubusercontent.com/67725/35265847-4fb02454-005c-11e8-9992-b12eff8ee5a3.jpg)

**Comment by tumashu** [comment]
The before discuss: https://github.com/melpa/melpa/issues/5246#event-1434282955

**Comment by Fuco1** [comment]
I think there is no reason not to use lexical binding, it makes more sense and often results in better performance.  `defvar` can always make dynamic bindings available so that's not a problem.


:+1:

**Comment by articuluxe** [comment]
This is fairly opinionated, is it not?  It’s not as if dynamic binding is wrong. You soon run the risk of giving so many stylistic suggestions that the user is overloaded, rather than sticking to outright errors.

**Comment by purcell** [comment]
> This is fairly opinionated, is it not? It’s not as if dynamic binding is wrong. You soon run the risk of giving so many stylistic suggestions that the user is overloaded, rather than sticking to outright errors.

Yes, it's certainly a little opinionated. One more obvious case would be to detect the use of the old deprecated `lexical-let` from `cl`, and suggest `lexical-binding` there instead. I make that suggestion regularly when reviewing MELPA packages, so that's what I'm most motivated to have `package-lint` report.

**Comment by purcell** [comment]
`package-lint` doesn't discourage `lexical-binding`, so this issue can be closed, I think.
